# Dataset name and version to path too
dataset: mixedphysics
dataset_ver: mixed_

# How much of the dataset to use
dataset_percent: 1.0

# Defining task IDs and total number of dynamics
task_ids: [0, 1, 2] #, 3, 4, 5, 6, 7, 8, 9, 10, 11]
num_dynamics: 3

# What splits to test over
testing_splits:
  - 0
  - 1
  - 2
  # - 3
  # - 4
  # - 5
  # - 6
  # - 7
  # - 8
  # - 9
  # - 10
  # - 11

# Dimension of the image [H, W]
dim: 32