# Number of training iterations
num_steps: 30000

# How often to log training and validation metrics
log_interval: 250
val_log_interval: 250

# What metrics to evaluate on during training
metrics:
  - vpt
  - recon_mse
  - dst

# What metrics to evaluate on at test-time
test_metrics:
  - vpt
  - recon_mse
  - dst

# Batch size
batch_size: 64
domain_size: 15
domain_varying: false

# Forcing test/val to .eval()
inference_mode: true

# Learning rate and cosine annealing scheduler
gradient_clip: 5
learning_rate: 1e-3
scheduler:
  use: true
  restart_interval: 7500
  warmup_steps: 200
  decay: 0.90

# KL loss betas
betas:
  z0: 1e-2
  kl: 1e-3

# How many steps are given for inference and to generate
z_amort: 3
generation_length: 20